{{- if and .Values.database.enabled .Values.database.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "medusa.fullname" . }}-postgres-pvc
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ .Values.database.persistence.accessMode | quote }}
  {{- if .Values.database.persistence.storageClassName }}
  storageClassName: {{ .Values.database.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
{{- end }}
