{{- if .Values.resourceQuota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "medusa.fullname" . }}-quota
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
spec:
  hard:
    {{- range $key, $value := .Values.resourceQuota.hard }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
