{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woocommerce.fullname" . }}-secrets
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.dbRootPassword }}
  db-root-password: {{ .Values.secrets.dbRootPassword | b64enc | quote }}
  {{- else }}
  db-root-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.wordpressKey }}
  wordpress-key: {{ .Values.secrets.wordpressKey | b64enc | quote }}
  {{- else }}
  wordpress-key: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- end }}
